---- 增加工号索引列增加工号索引列
ALTER TABLE c_gh ADD INDEX   idx_c_gh_ori_gh_parent_id(ori_gh_id,ori_gh_parent_id);

---- 增加多磅配置
DELETE FROM `weighing_images`.`s_product_params` WHERE (`id` = '93e7291a-0d2e-499f-9625-91e3415d9845');
DELETE FROM `weighing_images`.`s_product_params` WHERE (`id` = 'a1eaf156-2354-440f-a005-3840f2ae4f5d');
DELETE FROM `weighing_images`.`s_product_params` WHERE (`id` = '2f2477d7-9075-48ed-ade9-ee87a6b21595');
DELETE FROM `weighing_images`.`s_product_params` WHERE (`id` = '5fba2bb4-413b-4620-9e61-bb765a417a26');
INSERT INTO `weighing_images`.`s_product_params` (`id`, `is_enable`, `group_key`, `group_name`, `function_key`, `function_name`, `params_key`, `params_type`, `params_default_value`, `params_value`, `ui_config`, `sort`, `remark`, `creator_id`, `creator_name`, `created_at`, `modifier_id`, `modifier_name`, `updated_at`, `is_removed`) VALUES ('93e7291a-0d2e-499f-9625-91e3415d9845', '1', 'global', '全局设置', 'multiBalance', '多磅设置', 'mainPort ', 'number', '21', '21', '{\n                  \"label\": \"主操作机端口\",\n                  \"comp\": \"inputNumberComp\",\n                  \"position\": {\n                      \"spanNum\": 6\n                  },\n                  \"elmentConfig\": {\n                      \"disabled\": false,\n                      \"size\": \"small\",\n                      \"style\": {\n\n                      }\n                  },\n                  \"eventConf\": {\n                      \"isOn\": true,\n                      \"blur\": \"function(node, _this){_this.model.parent(_this.option.name)}\"\n                  }\n                  }', '25005', '主操作机端口', '62b7af0c-38e0-481d-bd3b-d57c448e1708', '超级管理员', '2021-09-26 10:26:32', '62b7af0c-38e0-481d-bd3b-d57c448e1708', '超级管理员', '2021-09-30 12:59:59', '0');
INSERT INTO `weighing_images`.`s_product_params` (`id`, `is_enable`, `group_key`, `group_name`, `function_key`, `function_name`, `params_key`, `params_type`, `params_default_value`, `params_value`, `ui_config`, `sort`, `remark`, `creator_id`, `creator_name`, `created_at`, `modifier_id`, `modifier_name`, `updated_at`, `is_removed`) VALUES ('a1eaf156-2354-440f-a005-3840f2ae4f5d', '1', 'global', '全局设置', 'multiBalance', '多磅设置', 'mainIp', 'string', '127.0.0.1', '172.16.20.14', '{\n                  \"label\": \"主操作机IP\",\n                  \"comp\": \"inputTextComp\",\n                  \"position\": {\n                      \"spanNum\": 6\n                  },\n                  \"elmentConfig\": {\n                      \"disabled\": false,\n                      \"size\": \"small\",\n                      \"style\": {\n\n                      }\n                  },\n                  \"eventConf\": {\n                      \"isOn\": true,\n                      \"blur\": \"function(node, _this){_this.model.parent(_this.option.name)}\"\n                  }\n                  }', '25004', '主操作机IP', '62b7af0c-38e0-481d-bd3b-d57c448e1708', '超级管理员', '2021-09-26 10:23:24', '62b7af0c-38e0-481d-bd3b-d57c448e1708', '超级管理员', '2021-09-28 17:53:49', '0');
INSERT INTO `weighing_images`.`s_product_params` (`id`, `is_enable`, `group_key`, `group_name`, `function_key`, `function_name`, `params_key`, `params_type`, `params_default_value`, `params_value`, `ui_config`, `sort`, `remark`, `creator_id`, `creator_name`, `created_at`, `modifier_id`, `modifier_name`, `updated_at`, `is_removed`) VALUES ('2f2477d7-9075-48ed-ade9-ee87a6b21595', '1', 'global', '全局设置', 'multiBalance', '多磅设置', 'ftpPassword', 'string', '    ', 'wodeququhaos', '{\n                  \"label\": \"FTP密码\",\n                  \"comp\": \"inputTextComp\",\n                  \"position\": {\n                      \"spanNum\": 6\n                  },\n                  \"elmentConfig\": {\n                      \"disabled\": false,\n                      \"size\": \"small\",\n                      \"style\": {\n\n                      }\n                  },\n                  \"eventConf\": {\n                      \"isOn\": true,\n                      \"blur\": \"function(node, _this){_this.model.parent(_this.option.name)}\"\n                  }\n                  }', '25002', 'FTP密码', '62b7af0c-38e0-481d-bd3b-d57c448e1708', '超级管理员', '2021-09-24 17:32:04', '62b7af0c-38e0-481d-bd3b-d57c448e1708', '超级管理员', '2021-09-28 17:54:28', '0');
INSERT INTO `weighing_images`.`s_product_params` (`id`, `is_enable`, `group_key`, `group_name`, `function_key`, `function_name`, `params_key`, `params_type`, `params_default_value`, `params_value`, `ui_config`, `sort`, `remark`, `creator_id`, `creator_name`, `created_at`, `modifier_id`, `modifier_name`, `updated_at`, `is_removed`) VALUES ('5fba2bb4-413b-4620-9e61-bb765a417a26', '1', 'global', '全局设置', 'multiBalance', '多磅设置', 'ftpUserName', 'string', 'LENOVO', 'YUANYUAN.HU', '{\n                  \"label\": \"FTP用户名\",\n                  \"comp\": \"inputTextComp\",\n                  \"position\": {\n                      \"spanNum\": 6\n                  },\n                  \"elmentConfig\": {\n                      \"disabled\": false,\n                      \"size\": \"small\",\n                      \"style\": {\n\n                      }\n                  },\n                  \"eventConf\": {\n                      \"isOn\": true,\n                      \"blur\": \"function(node, _this){_this.model.parent(_this.option.name)}\"\n                  }\n                  }', '25001', 'FTP用户名', '62b7af0c-38e0-481d-bd3b-d57c448e1708', '超级管理员', '2021-09-24 17:29:14', '62b7af0c-38e0-481d-bd3b-d57c448e1708', '超级管理员', '2021-09-29 15:44:16', '0');


---- 更新版本号
LOCK TABLES `database_version` WRITE;
insert into database_version(version,created_at)
values ('1.0.9', now())
ON DUPLICATE KEY UPDATE version='1.0.9';
UNLOCK TABLES;

