name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run ci
    - run: npm install codecov
    - name: Upload coverage to Codecov
      run: ./node_modules/.bin/codecov
    - run: curl -s https://codecov.io/bash