"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.path = exports.color = exports.vector = exports.matrix = exports.OrientedBoundingRect = exports.BoundingRect = exports.Pattern = exports.RadialGradient = exports.LinearGradient = exports.TrochoidShape = exports.Trochoid = exports.StarShape = exports.Star = exports.SectorShape = exports.Sector = exports.RoseShape = exports.Rose = exports.RingShape = exports.Ring = exports.RectShape = exports.Rect = exports.PolylineShape = exports.Polyline = exports.PolygonShape = exports.Polygon = exports.LineShape = exports.Line = exports.IsogonShape = exports.Isogon = exports.HeartShape = exports.Heart = exports.EllipseShape = exports.Ellipse = exports.DropletShape = exports.Droplet = exports.CircleShape = exports.Circle = exports.BezierCurveShape = exports.BezierCurve = exports.ArcShape = exports.Arc = exports.Text = exports.IncrementalDisplayable = exports.TSpan = exports.CompoundPath = exports.Image = exports.Path = exports.Group = exports.Element = exports.Point = void 0;
exports.showDebugDirtyRect = exports.parseSVG = exports.morph = exports.util = void 0;
var zrUtil = require("./core/util");
exports.util = zrUtil;
var matrix = require("./core/matrix");
exports.matrix = matrix;
var vector = require("./core/vector");
exports.vector = vector;
var colorTool = require("./tool/color");
exports.color = colorTool;
var pathTool = require("./tool/path");
exports.path = pathTool;
var parseSVG_1 = require("./tool/parseSVG");
exports.parseSVG = parseSVG_1.parseSVG;
var morphPathTool = require("./tool/morphPath");
exports.morph = morphPathTool;
var Point_1 = require("./core/Point");
__createBinding(exports, Point_1, "default", "Point");
var Element_1 = require("./Element");
__createBinding(exports, Element_1, "default", "Element");
var Group_1 = require("./graphic/Group");
__createBinding(exports, Group_1, "default", "Group");
var Path_1 = require("./graphic/Path");
__createBinding(exports, Path_1, "default", "Path");
var Image_1 = require("./graphic/Image");
__createBinding(exports, Image_1, "default", "Image");
var CompoundPath_1 = require("./graphic/CompoundPath");
__createBinding(exports, CompoundPath_1, "default", "CompoundPath");
var TSpan_1 = require("./graphic/TSpan");
__createBinding(exports, TSpan_1, "default", "TSpan");
var IncrementalDisplayable_1 = require("./graphic/IncrementalDisplayable");
__createBinding(exports, IncrementalDisplayable_1, "default", "IncrementalDisplayable");
var Text_1 = require("./graphic/Text");
__createBinding(exports, Text_1, "default", "Text");
var Arc_1 = require("./graphic/shape/Arc");
__createBinding(exports, Arc_1, "default", "Arc");
__createBinding(exports, Arc_1, "ArcShape");
var BezierCurve_1 = require("./graphic/shape/BezierCurve");
__createBinding(exports, BezierCurve_1, "default", "BezierCurve");
__createBinding(exports, BezierCurve_1, "BezierCurveShape");
var Circle_1 = require("./graphic/shape/Circle");
__createBinding(exports, Circle_1, "default", "Circle");
__createBinding(exports, Circle_1, "CircleShape");
var Droplet_1 = require("./graphic/shape/Droplet");
__createBinding(exports, Droplet_1, "default", "Droplet");
__createBinding(exports, Droplet_1, "DropletShape");
var Ellipse_1 = require("./graphic/shape/Ellipse");
__createBinding(exports, Ellipse_1, "default", "Ellipse");
__createBinding(exports, Ellipse_1, "EllipseShape");
var Heart_1 = require("./graphic/shape/Heart");
__createBinding(exports, Heart_1, "default", "Heart");
__createBinding(exports, Heart_1, "HeartShape");
var Isogon_1 = require("./graphic/shape/Isogon");
__createBinding(exports, Isogon_1, "default", "Isogon");
__createBinding(exports, Isogon_1, "IsogonShape");
var Line_1 = require("./graphic/shape/Line");
__createBinding(exports, Line_1, "default", "Line");
__createBinding(exports, Line_1, "LineShape");
var Polygon_1 = require("./graphic/shape/Polygon");
__createBinding(exports, Polygon_1, "default", "Polygon");
__createBinding(exports, Polygon_1, "PolygonShape");
var Polyline_1 = require("./graphic/shape/Polyline");
__createBinding(exports, Polyline_1, "default", "Polyline");
__createBinding(exports, Polyline_1, "PolylineShape");
var Rect_1 = require("./graphic/shape/Rect");
__createBinding(exports, Rect_1, "default", "Rect");
__createBinding(exports, Rect_1, "RectShape");
var Ring_1 = require("./graphic/shape/Ring");
__createBinding(exports, Ring_1, "default", "Ring");
__createBinding(exports, Ring_1, "RingShape");
var Rose_1 = require("./graphic/shape/Rose");
__createBinding(exports, Rose_1, "default", "Rose");
__createBinding(exports, Rose_1, "RoseShape");
var Sector_1 = require("./graphic/shape/Sector");
__createBinding(exports, Sector_1, "default", "Sector");
__createBinding(exports, Sector_1, "SectorShape");
var Star_1 = require("./graphic/shape/Star");
__createBinding(exports, Star_1, "default", "Star");
__createBinding(exports, Star_1, "StarShape");
var Trochoid_1 = require("./graphic/shape/Trochoid");
__createBinding(exports, Trochoid_1, "default", "Trochoid");
__createBinding(exports, Trochoid_1, "TrochoidShape");
var LinearGradient_1 = require("./graphic/LinearGradient");
__createBinding(exports, LinearGradient_1, "default", "LinearGradient");
var RadialGradient_1 = require("./graphic/RadialGradient");
__createBinding(exports, RadialGradient_1, "default", "RadialGradient");
var Pattern_1 = require("./graphic/Pattern");
__createBinding(exports, Pattern_1, "default", "Pattern");
var BoundingRect_1 = require("./core/BoundingRect");
__createBinding(exports, BoundingRect_1, "default", "BoundingRect");
var OrientedBoundingRect_1 = require("./core/OrientedBoundingRect");
__createBinding(exports, OrientedBoundingRect_1, "default", "OrientedBoundingRect");
var showDebugDirtyRect_1 = require("./debug/showDebugDirtyRect");
__createBinding(exports, showDebugDirtyRect_1, "default", "showDebugDirtyRect");
